### ISSUE TITLE
動く床の上で視点移動がうまく行えない問題

### ISSUE THREAD

**Issue by ryosebach** [tai-mm/UnitychanActions#5]
解決いたしました

![aaa-iloveimg-compressed 1](https://user-images.githubusercontent.com/15684002/36032407-3e995b70-0df1-11e8-9262-3d849723d81b.gif)

**Comment by tai-mm** [comment]
ありがとうございます( ;∀;)

**Comment by tai-mm** [comment]
結局、何が原因でしたか....？

**Comment by ryosebach** [comment]
https://github.com/tai-mm/UnitychanActions/blob/5c5c9223953ef3e51f921dbebff8f0a756ba6307/Assets/UnityChanAction/Scripts/ScriptsWithStage/Entities/EntityAIUnityChanMoves.cs#L121

ここで作っているPlaneがlocalPositionで作っているから，床の上に乗った時に子オブジェクトにしているため常に0,0,0で作られていておかしなことになっているみたいね．

なのでここを`transform.position`にすれば解決でーす 🙉 🙉

**Comment by tai-mm** [comment]
なるほど、ワールド座標ではなく`transform.localPosition`になっていたから親オブジェクトの影響をうけていたのですね…。気づきませんでした。
ありがとうございました( ;∀;)
